#!/usr/bin/env ruby

require 'fileutils'

def current_file(*name)
  pwd = Dir.getwd
  File.join(pwd, *name)
end

def home_file(*name)
  File.join(ENV.fetch('HOME'), *name)
end

def symlink(from, to)
  FileUtils.rm_rf(to)
  File.symlink(from, to)
end

files = {
  current_file('.zshenv') => home_file('.zshenv'),
  current_file('.zshrc') => home_file('.zshrc'),
  current_file('jenv') => home_file('.jenv'),
  current_file('dircolors-solarized', 'dircolors.256dark') => home_file('.dir_colors'),
  current_file('.gitconfig') => home_file('.gitconfig'),
  current_file('.gitignore') => home_file('.gitignore'),
  current_file('.vimrc.before') => home_file('.vimrc.before'),
  current_file('.vimrc.after') => home_file('.vimrc.after'),
  current_file('.ackrc') => home_file('.ackrc'),
  current_file('.irbrc') => home_file('.irbrc'),
  current_file('.psqlrc') => home_file('.psqlrc'),
  current_file('.tmux.conf') => home_file('.tmux.conf'),
  current_file('.janus') => home_file('.janus'),
  current_file('.gemrc') => home_file('.gemrc'),
  current_file('.emacs.d') => home_file('.emacs.d'),
  current_file('vim-go') => home_file('.janus', 'vim-go'),
  current_file('tabular') => home_file('.janus', 'tabular'),
  current_file('vimux') => home_file('.janus', 'vimux'),
  current_file('vimux-ruby-test') => home_file('.janus', 'vimux-ruby-test'),
  current_file('dart-vim-plugin') => home_file('.janus', 'dart-vim-plugin'),
  current_file('vim-airline') => home_file('.janus', 'vim-airline'),
  current_file('vim-airline-themes') => home_file('.janus', 'vim-airline-themes'),
  current_file('vim-fireplace') => home_file('.janus', 'vim-fireplace'),
  current_file('vim-gradle') => home_file('.janus', 'vim-gradle'),
  current_file('vim-dispatch') => home_file('.janus', 'vim-dispatch'),
  current_file('vim-jsx') => home_file('.janus', 'vim-jsx')
}

files.each do |from, to|
  puts "#{from} => #{to}"
  symlink(from, to)
end

puts

go_packs = [
  'github.com/tools/godep',
  'github.com/jingweno/odt',
]

go_packs.each do |go_pack|
  cmd = "go get -u #{go_pack}"
  puts cmd
  `#{cmd}`
end
