#!/usr/bin/env bash

rm -rf $HOME/.zshenv
ln -s $(pwd)/.zshenv $HOME/.zshenv

rm -rf $HOME/.zshrc
ln -s $(pwd)/.zshrc $HOME/.zshrc

rm -rf $HOME/.dir_colors
ln -s $(pwd)/dircolors-solarized/dircolors.256dark $HOME/.dir_colors

rm -f $HOME/.gitconfig
ln -s $(pwd)/.gitconfig $HOME/.gitconfig

rm -f $HOME/.gitignore
ln -s $(pwd)/.gitignore $HOME/.gitignore

rm -rf $HOME/.vimrc.before
ln -s $(pwd)/.vimrc.before $HOME/.vimrc.before

rm -rf $HOME/.vimrc.after
ln -s $(pwd)/.vimrc.after $HOME/.vimrc.after

rm -rf $HOME/.ackrc
ln -s $(pwd)/.ackrc $HOME/.ackrc

rm -rf $HOME/.tmux.conf
ln -s $(pwd)/.tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.janus
ln -s $(pwd)/.janus $HOME/.janus

rm -rf $HOME/.gemrc
ln -s $(pwd)/.gemrc $HOME/.gemrc

rm -rf $HOME/.emacs.d
ln -s $(pwd)/.emacs.d $HOME/.emacs.d

rm -rf $HOME/.janus/go
ln -s $(brew --prefix go)/misc/vim $HOME/.janus/go

rm -rf $HOME/.janus/gocode
ln -s $(pwd)/gocode/vim $HOME/.janus/gocode

rm -rf $HOME/.janus/asciidoc-vim
mkdir -p $HOME/.janus/asciidoc-vim/syntax
ln -s $(pwd)/asciidoc-vim/asciidoc.vim $(pwd)/.janus/asciidoc-vim/syntax/asciidoc.vim

rm -rf $HOME/.janus/tabular
ln -s $(pwd)/tabular $(pwd)/.janus/tabular

rm -rf $HOME/.janus/vimux
ln -s $(pwd)/vimux $(pwd)/.janus/vimux

rm -rf $HOME/.janus/vimux-ruby-test
ln -s $(pwd)/vimux-ruby-test $(pwd)/.janus/vimux-ruby-test
