#!/usr/bin/env bash

rm -rf $HOME/.zshrc
ln -s $(pwd)/.zshrc $HOME/.zshrc

rm -rf $HOME/.dir_colors
ln -s $(pwd)/dircolors-solarized/dircolors.256dark $HOME/.dir_colors

rm -f $HOME/.gitconfig
ln -s $(pwd)/.gitconfig $HOME/.gitconfig

rm -rf $HOME/.vimrc.before
ln -s $(pwd)/.vimrc.before $HOME/.vimrc.before

rm -rf $HOME/.vimrc.after
ln -s $(pwd)/.vimrc.after $HOME/.vimrc.after

rm -rf $HOME/.ackrc
ln -s $(pwd)/.ackrc $HOME/.ackrc

rm -rf $HOME/.janus
ln -s $(pwd)/.janus $HOME/.janus

rm -rf $HOME/.gemrc
ln -s $(pwd)/.gemrc $HOME/.gemrc

rm -rf $HOME/.emacs.d
ln -s $(pwd)/.emacs.d $HOME/.emacs.d

rm -rf $HOME/.janus/go
mkdir -p $HOME/.janus
ln -s $(brew --prefix go)/misc/vim $HOME/.janus/go
